# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-stability pipeline (for the purpose of detecting intermittent and flaky failures)

name: $(Build.BuildId)

trigger: none
pr: none

parameters:
- name: poolBuild
  type: object
  default: Large

- name: stageNames
  type: object
  default:
  - Test1

- name: taskBuild
  type: string
  default: ci:build

- name: checkoutSubmodules
  type: boolean
  default: true

schedules:
  - cron: "00 03 * * SUN"
    displayName: Scheduled Tests weekly at Saturday night
    branches:
      include:
      - main
      - next
    always: true

variables:
- group: prague-key-vault
  # We use 'chalk' to colorize output, which auto-detects color support in the
  # running terminal.  The log output shown in Azure DevOps job runs only has
  # basic ANSI color support though, so force that in the pipeline
- name: FORCE_COLOR
  value: 1
- name: pnpmStorePath
  value: $(Pipeline.Workspace)/.pnpm-store

stages:
  - ${{ each stageName in parameters.stageNames }}:
    - stage:
      displayName: ${{ stageName }}
      dependsOn: []
      jobs:
      - template: templates/include-test-stability.yml
        parameters:
          packageManagerInstallCommand: 'pnpm i --frozen-lockfile'
          packageManager: pnpm
          buildDirectory: .
          poolBuild: ${{ parameters.poolBuild }}
          checkoutSubmodules: ${{ parameters.checkoutSubmodules }}
          timeoutInMinutes: 360
          taskBuild : ${{ parameters.taskBuild }}
          taskLint: false
          taskTest: 
          - ci:test:mocha
          - ci:test:jest
          - ci:test:realsvc:local:full
          - ci:test:realsvc:tinylicious:full
          - ci:test:stress:tinylicious
          - test:copyresults
          stageName: ${{ stageName }}
